version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
  build:
    commands:
      - docker build -t public.ecr.aws/t7a4n4t7/backend:latest ./django/Dockerfile
      - docker build -t public.ecr.aws/t7a4n4t7/frontend:latest ./react/Dockerfile
  post_build:
    commands:
      - docker push public.ecr.aws/t7a4n4t7/backend:latest
      - docker push public.ecr.aws/t7a4n4t7/backend:latest
