version: 0.2

env:
  secrets-manager:
    DOCKERHUB_PASS: "/dockerhub/credentials:password"
    DOCKERHUB_USER: "/dockerhub/credentials:username"

phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.8
    commands:
      - pip install git-remote-codecommit
  pre_build:
    commands:
      - echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USER --password-stdin
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 712577856580.dkr.ecr.us-east-1.amazonaws.com
      - git clone codecommit::us-east-1://ComicsDocker
  build:
    commands:
      - docker build -t 712577856580.dkr.ecr.us-east-1.amazonaws.com/backend -f ./django/Dockerfile .
      - docker build -t 712577856580.dkr.ecr.us-east-1.amazonaws.com/frontend -f ./react/Dockerfile .
  post_build:
    commands:
      - docker push 712577856580.dkr.ecr.us-east-1.amazonaws.com/backend
      - docker push 712577856580.dkr.ecr.us-east-1.amazonaws.com/frontend

artifacts:
  files:
    - cloudformation-docker.yml
