version: 0.2

env:
  secrets-manager:
    DOCKERHUB_PASS: "/dockerhub/credentials:password"
    DOCKERHUB_USER: "/dockerhub/credentials:username"

phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.8
    commands:
      - pip install git-remote-codecommit
  pre_build:
    commands:
      - echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USER --password-stdin
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - git clone codecommit::us-east-1://ComicsDocker
  build:
    commands:
      - docker build -t public.ecr.aws/t7a4n4t7/backend -f ./django/Dockerfile .
      - docker build -t public.ecr.aws/t7a4n4t7/frontend -f ./react/Dockerfile .
  post_build:
    commands:
      - docker push public.ecr.aws/t7a4n4t7/backend
      - docker push public.ecr.aws/t7a4n4t7/frontend

artifacts:
  files:
    - appspec.yml
    - scripts/deploy_app
